name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch (usually 'main' or 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload static files
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./  # The path where your static site files are stored

  deploy_static_files:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1